### PR TITLE
Feature/newsletter component

### PR DESCRIPTION
**Pull request by stifamajstor**
Napravio sam Newsletter komponentu i form. Oboje su u istom fileu.

Forma nije stilizirana, nisam znao kako zelite.

CSS code koji je bio u fileu sam komentirao.

Newsletter radi, testirao sam, ali komponenta nije trenutno pozvana nigdje jer nisam znao gdje ju zelite.

Bas mi je cudno pisati commente za PR na HR :laughing:

Screenshot 2021-08-27 at 21 28 41

### CODE REVIEW

**Comment by filip-strelec** [comment]
budem ja sutra(danas) mergeal, bil sam u vz-u danas

**Review by filip-strelec — CHANGES_REQUESTED** [review]
Still not rdy, needs the validation msg on success and needs style (you can check the hidden component newsletter on landing page, how I styled it..) the "click to update profile" (when the user types the same mail 2nd time also needs style)
Overall, it's working, nice job @stifamajstor

**Comment by filip-strelec** [comment]
> Prije neg se merga trebalo bi odradity styling, pozvati komponentu.
> Neznam kak ste mislili al bilo bi cool da se taj "subscribe to the newsletter form" pojavljuje ko modal (popup).
> 
> E da, iz nekog razloga env varijabla ne radi u reactu, pa sam stavil URL direktno.

zasad, dok nismo poznati to je ok, kasnije bi mogli dici neki backend server, s  env varijablama, i custom endpointovoima za fetch podatakak iz blockchaina i slicno... ja sam digel db sync (postgres bazu i tool db sync koji se synca s bazom) (s postgREST endpointovima), bilo bi fora to ukomponirati u page nekad

**Comment by filip-strelec** [comment]
> Neznam kak ste mislili al bilo bi cool da se taj "subscribe to the newsletter form" pojavljuje ko modal (popup).


@stifamajstor sure, ako ti se da mozes kak god oces

**Comment by stifamajstor** [comment]
Component is finished. ✅
If the user subscribes or rejects the newsletter, the information will be saved in local storage. 
If user rejects, the newsletter will show only when the user returns with a new session and only if the random number generator returned no. 1 (out of three).

I also removed the newsletter from the navbar and removed the CPU token page like Filip suggested in Telegram chat.

**Review by filip-strelec — APPROVED** [review]

**Pull request merged**
